steps:
  - input: "Which flatbuild do you need?  Please provide the name, e.g., 8295_FlatBuild_49-20241115.tgz"
    fields:
      - text: "Flatbuild Name"
        key: "flatbuild_name"
  - label: "Run script"
    command: script.cmd
